export default {
    icon1: "/static/image/index-icon-1.jpg",
    icon2: "/static/image/index-icon-2.jpg",
    icon3: "/static/image/index-icon-3.jpg",
    langzh: "/static/image/lang-zh.png",
    langen: "/static/image/lang-en.png",
    langtw:  "/static/image/lang-tw.png",
    langrb: "/static/image/lang-rb.png",
    zhsz: "/static/image/icon-zhsz.png",
    jtrz: "/static/image/icon-jyrz.png",
    sfrz: "/static/image/icon-sfrz.png",
    iconchecked: "/static/image/icon-checked.png",
    iconcheck: "/static/image/icon-check.png",
    iconbg: '/static/image/index-bg.png',
    indexphone: '/static/image/index-phone.png',
}